import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,unlink} from 'node:fs/promises';
import {resolve,sep} from 'node:path';
const base='http://localhost:4173';
const requestId=randomUUID();
const body={requestId,name:'Тест локальной формы',phone:'+7 (999) 000-00-00',consent:true,form:'contact',attribution:{utm_source:'local-test'}};
const send=(value,origin=base)=>fetch(base+'/api/leads',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(value)});
assert.equal((await fetch(base+'/')).status,200);
assert.equal((await fetch(base+'/nonexistent-page/')).status,404);
assert.equal((await fetch(base+'/data/leads/')).status,404);
assert.equal((await fetch(base+'/api/leads')).status,405);
assert.equal((await send(body,'https://unrelated.example')).status,403);
assert.equal((await send({...body,phone:'123'})).status,400);
const response=await send(body);assert.equal(response.status,200);assert.equal((await response.json()).mode,'preview');
const duplicate=await send(body);assert.equal(duplicate.status,200);
const storageRoot=resolve('data/leads');const file=resolve(storageRoot,requestId+'.json');assert.ok(file.startsWith(storageRoot+sep));
assert.equal(JSON.parse(await readFile(file,'utf8')).attribution.utm_source,'local-test');await unlink(file);
console.log('PASS: HTTP routes, 404, private data, method/origin/phone validation, preview save, UTM, duplicate submission. Test record removed.');
