// Weather/daylight variants of generated BEFORE images only. Originals and AFTER images are preserved.
export const beforeWeatherAssets = {
  "before-hardware-v4/finish-turnkey-015-no-hardware.png": "before-weather-v1/before-001.webp", // early-morning
  "before-hardware-v4/finish-turnkey-004-no-hardware.png": "before-weather-v1/before-002.webp", // overcast-noon
  "before-hardware-v4/finish-turnkey-018-no-hardware.png": "before-weather-v1/before-003.webp", // morning-haze
  "before-hardware-v4/finish-turnkey-019-no-hardware.png": "before-weather-v1/before-005.webp", // cloudy-morning
  "before-hardware-v4/finish-turnkey-013-no-hardware.png": "before-weather-v1/before-006.webp", // light-rain
  "before-hardware-v4/finish-turnkey-002-no-hardware.png": "before-weather-v1/before-007.webp", // early-morning
  "before-hardware-v4/finish-turnkey-014-no-hardware.png": "before-weather-v1/before-008.webp", // overcast-noon
  "before-hardware-v4/finish-turnkey-003-no-hardware.png": "before-weather-v1/before-009.webp", // morning-haze
  "before-hardware-v4/finish-turnkey-017-no-hardware.png": "before-weather-v1/before-010.webp", // late-afternoon
  "before-hardware-v4/finish-turnkey-006-no-hardware.png": "before-weather-v1/before-011.webp", // cloudy-morning
  "before-daytime/before-013.webp": "before-weather-v1/before-012.webp", // light-rain
  "before-daytime/before-014.webp": "before-weather-v1/before-015.webp", // morning-haze
  "before-daytime/before-028.webp": "before-weather-v1/before-020.webp", // overcast-noon
  "before-daytime/before-029.webp": "before-weather-v1/before-021.webp", // morning-haze
  "before-hardware-v4/finish-turnkey-021-no-hardware.png": "before-weather-v1/before-027.webp", // morning-haze
  "before-hardware-v4/finish-turnkey-008-no-hardware.png": "before-weather-v1/before-029.webp", // cloudy-morning
  "before-hardware-v4/finish-turnkey-009-no-hardware.png": "before-weather-v1/before-030.webp", // light-rain
  "before-hardware-v4/finish-turnkey-010-no-hardware.png": "before-weather-v1/before-031.webp", // early-morning
  "before-hardware-v4/finish-turnkey-011-no-hardware.png": "before-weather-v1/before-032.webp", // overcast-noon
  "before-hardware-v4/finish-turnkey-012-no-hardware.png": "before-weather-v1/before-033.webp", // morning-haze
  "before-hardware-v4/finish-turnkey-022-no-hardware.png": "before-weather-v1/before-035.webp", // cloudy-morning
  "before-hardware-v4/finish-turnkey-023-no-hardware.png": "before-weather-v1/before-036.webp", // light-rain
  "before-hardware-v4/finish-turnkey-024-no-hardware.png": "before-weather-v1/before-037.webp", // early-morning
  "service-before-after/turnkey-electrical-02-before-v2.webp": "before-weather-v1/before-039.webp", // morning-haze
  "service-before-after/turnkey-furniture-04-before-v3.webp": "before-weather-v1/before-040.webp", // late-afternoon
  "service-before-after/turnkey-electrical-05-before-v2.webp": "before-weather-v1/before-041.webp", // cloudy-morning
  "service-before-after/turnkey-furniture-09-before-v2.webp": "before-weather-v1/before-042.webp", // light-rain
  "service-before-after/turnkey-electrical-10-before-v2.webp": "before-weather-v1/before-043.webp", // early-morning
  "service-before-after/balcony-roof-3-before.jpg": "before-weather-v1/before-044.webp", // early-morning
  "service-before-after/balcony-roof-4-before.jpg": "before-weather-v1/before-045.webp", // morning-haze
  "service-before-after/balcony-roof-2-before.jpg": "before-weather-v1/before-046.webp", // late-afternoon
  "service-before-after/furniture-interior-v2-01-before.webp": "before-weather-v1/before-047.webp", // cloudy-morning
  "service-before-after/furniture-interior-v2-04-before.webp": "before-weather-v1/before-048.webp", // light-rain
  "service-before-after/furniture-interior-v2-07-before.webp": "before-weather-v1/before-049.webp", // overcast-noon
  "service-before-after/furniture-interior-v2-09-before.webp": "before-weather-v1/before-050.webp", // overcast-noon
  "service-before-after/furniture-interior-v2-10-before.webp": "before-weather-v1/before-051.webp", // morning-haze
  "service-before-after/furniture-interior-v2-12-before.webp": "before-weather-v1/before-052.webp", // overcast-noon
  "service-before-after/furniture-interior-v2-02-before.webp": "before-weather-v1/before-053.webp", // cloudy-morning
  "service-before-after/furniture-interior-v2-03-before.webp": "before-weather-v1/before-054.webp", // light-rain
  "service-before-after/furniture-interior-v2-05-before.webp": "before-weather-v1/before-055.webp", // cloudy-morning
  "service-before-after/furniture-interior-v2-06-before.webp": "before-weather-v1/before-056.webp", // overcast-noon
  "service-before-after/furniture-interior-v2-08-before.webp": "before-weather-v1/before-057.webp", // morning-haze
  "service-before-after/furniture-interior-v2-11-before.webp": "before-weather-v1/before-058.webp", // overcast-noon
  "electrical-v2/el1Before.webp": "before-weather-v1/before-059.webp", // early-morning
  "electrical-v2/el2Before.webp": "before-weather-v1/before-060.webp", // light-rain
  "electrical-v2/el5Before.webp": "before-weather-v1/before-062.webp", // early-morning
  "electrical-v2/el10Before.webp": "before-weather-v1/before-063.webp", // morning-haze
  "electrical-v2/el12Before.webp": "before-weather-v1/before-064.webp", // late-afternoon
  "electrical-v2/el4Before.webp": "before-weather-v1/before-065.webp", // early-morning
  "electrical-v2/el6Before.webp": "before-weather-v1/before-066.webp", // light-rain
  "electrical-v2/el7Before.webp": "before-weather-v1/before-067.webp", // early-morning
  "electrical-v2/el8Before.webp": "before-weather-v1/before-068.webp", // overcast-noon
  "electrical-v2/el9Before.webp": "before-weather-v1/before-069.webp", // morning-haze
  "electrical-v2/el11Before.webp": "before-weather-v1/before-070.webp", // late-afternoon
  "before-hardware-v2/before-112.webp": "before-weather-v1/before-083.webp", // cloudy-morning
  "before-hardware-v2/before-113.webp": "before-weather-v1/before-084.webp", // light-rain
  "before-daytime/before-115.webp": "before-weather-v1/before-085.webp", // overcast-noon
  "before-daytime/before-125.webp": "before-weather-v1/before-096.webp", // light-rain
  "service-before-after/cold-ordinary-05-before.webp": "before-weather-v1/before-098.webp", // overcast-noon
  "service-before-after/warm-loggia-aged-03-before-clean-v3.png": "before-weather-v1/before-114.webp", // light-rain
  "service-before-after/warm-loggia-aged-08-before-straight-sill-torn-linoleum.png": "before-weather-v1/before-118.webp", // late-afternoon
  "before-daytime/before-121.webp": "before-weather-v1/before-121.webp", // overcast-noon
  "service-before-after/panoramic-long-angle-before.webp": "before-weather-v1/before-124.webp", // late-afternoon
  "service-before-after/loggia-angled-06-before.webp": "before-weather-v1/before-128.webp", // overcast-noon
};
