import {company,prices,projects,beforeAfterProjects,serviceBeforeAfterProjects,services,serviceSeo,faqs,integrations} from './content.mjs';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headingWithLocation=value=>esc(value).replace(/в Москве и Московской области/g,'<span class="location-accent">в Москве и Московской области</span>');
export const money=v=>v===null?'По проекту':`от ${v.toLocaleString('ru-RU')} ₽`;
export const arrow='<span aria-hidden="true">↗</span>';
const buttonArrow='<span aria-hidden="true">→</span>';
const iconPaths={
 'osteklenie-balkonov':'<rect x="3" y="3" width="18" height="18" rx="1"/><path d="M12 3v18M3 12h18"/>',
 'uteplenie-balkonov':'<path d="M4 5h16v14H4zM8 5v14M16 5v14M4 10h16M4 14h16"/>',
 'otdelka-balkonov':'<path d="M4 19V5h16v14M8 5v14M16 5v14M4 12h16"/>',
 'balkon-pod-klyuch':'<path d="m3 11 9-7 9 7M5 10v10h14V10M9 20v-6h6v6"/>',
 'osteklenie-lodzhii':'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="M9 4v16M15 4v16M3 12h18"/>',
 'uteplenie-lodzhii':'<path d="M3 5h18v14H3zM7 5v14M12 5v14M17 5v14M3 10h18M3 15h18"/>',
 'otdelka-lodzhii':'<path d="M4 20V4h16v16M8 4v16M16 4v16M4 12h16"/>',
 'lodzhiya-pod-klyuch':'<path d="M3 6h18v14H3zM7 6v14M17 6v14M7 14h10M10 10h4"/>',
 'krysha-nad-balkonom':'<path d="m3 11 9-7 9 7M5 11h14M7 11v9M17 11v9M5 20h14"/>',
 'mebel-dlya-balkona':'<path d="M5 4h14v16H5zM5 11h14M9 7h2M9 15h2"/>',
 'elektrika-na-balkone':'<path d="M13 2 6 13h6l-1 9 7-12h-6l1-8Z"/>',
 'obedinenie-balkona-s-komnatoj':'<path d="M3 4h7v16H3zM14 4h7v16h-7zM10 12h4M8 10l2 2-2 2M16 10l-2 2 2 2"/>',
 'osteklenie-kottedzhej':'<path d="m3 11 9-7 9 7v9H3zM8 20v-6h8v6M6 11h12"/>'
};
export const serviceIcon=slug=>`<svg class="service-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${iconPaths[slug]||iconPaths['balkon-pod-klyuch']}</svg>`;
const serviceVisuals={
 'osteklenie-balkonov':['balcony-glazing.jpg','Выступающий остеклённый балкон с открытым городским видом'],
 'uteplenie-balkonov':['balcony-insulation.jpg','Утепление стен, пола и потолка выступающего балкона'],
 'otdelka-balkonov':['balcony-finishing.jpg','Отделанный деревом выступающий балкон с продуманным освещением'],
 'balkon-pod-klyuch':['balcony-turnkey.jpg','Готовый выступающий балкон с рабочей зоной и местом для отдыха'],
 'osteklenie-lodzhii':['card-glazing.webp','Остекление просторной лоджии, встроенной в объём здания'],
 'uteplenie-lodzhii':['card-insulation.webp','Утепление стен, пола, потолка и парапета встроенной лоджии'],
 'otdelka-lodzhii':['card-finishing.webp','Отделка встроенной лоджии натуральным деревом и мягким светом'],
 'lodzhiya-pod-klyuch':['card-turnkey.webp','Готовая встроенная лоджия с рабочей зоной и местом для отдыха'],
 'krysha-nad-balkonom':['concept-roof.jpg','Дизайн-концепт современной крыши над остеклённым балконом'],
 'mebel-dlya-balkona':['concept-furniture.jpg','Дизайн-концепт встроенного шкафа, скамьи и компактного стола на балконе'],
 'elektrika-na-balkone':['concept-electrics.jpg','Дизайн-концепт тёплого освещения и электрических точек на балконе'],
 'obedinenie-balkona-s-komnatoj':['concept-room.jpg','Дизайн-концепт светлой гостиной, объединённой с утеплённой лоджией'],
 'osteklenie-kottedzhej':['concept-cottage.jpg','Дизайн-концепт панорамного остекления веранды загородного дома']
};
const serviceImage=s=>{const [name,alt]=serviceVisuals[s.slug];return `<img src="/assets/${name}" width="960" height="640" loading="lazy" decoding="async" alt="${esc(alt)}">`;};
export const button=(label,href='#quiz',extra='')=>`<a class="button ${extra}" href="${href}">${label} ${buttonArrow}</a>`;
const pictureAsset=(name,suffix='')=>{const match=name.match(/^(.*)(\.[^.]+)$/);return match?`${match[1]}${suffix}${match[2]}`:`${name}${suffix}.webp`;};
export function pic(name,alt,classes='',eager=false){const src=pictureAsset(name);const small=pictureAsset(name,'-small');return `<img class="${classes}" src="/assets/${src}" srcset="/assets/${small} 480w, /assets/${src} 1000w" sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1000px) 50vw, 600px" width="1000" height="1100" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async" alt="${esc(alt)}">`;}
export const brand=`<a class="brand" href="/" aria-label="ArtBalkon — главная"><img class="brand-logo" src="/assets/artbalkon-logo.svg" width="461" height="132" alt="ArtBalkon"></a>`;
const headerMessengers=extra=>`<div class="header-messengers ${extra||''}" aria-label="Написать в мессенджер"><a class="header-messenger telegram-messenger" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click" aria-label="Написать в Telegram"><img src="/assets/telegram-logo.svg" width="128" height="128" alt="Telegram"></a><a class="header-messenger max-messenger" href="${company.max}" target="_blank" rel="noopener" aria-label="Написать в MAX"><img src="/assets/max-app-icon.png" width="250" height="250" alt="MAX"></a></div>`;
const socialIconLinks=extra=>`<div class="social-icon-links ${extra||''}" aria-label="Связаться в мессенджерах"><a class="social-icon-link social-icon-telegram" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click" aria-label="Написать в Telegram"><img src="/assets/telegram-logo.svg" width="128" height="128" alt="Telegram"></a><a class="social-icon-link social-icon-max" href="${company.max}" target="_blank" rel="noopener" aria-label="Написать в MAX"><img src="/assets/max-app-icon.png" width="250" height="250" alt="MAX"></a><a class="social-icon-link social-icon-vk" href="${company.vk}" target="_blank" rel="noopener" aria-label="Открыть ВКонтакте"><img src="/assets/vk-logo.svg" width="48" height="48" alt="ВКонтакте"></a></div>`;
export function header(){return `<a class="skip-link" href="#main">Перейти к содержанию</a><header class="site-header"><div class="container header-inner">${brand}<nav class="desktop-nav" aria-label="Основная навигация"><a href="/">Главная</a><a href="/#services">Услуги</a><a href="/nashi-raboty/">Наши работы</a><a href="/#prices">Цены</a><a href="/#reviews">Отзывы</a><a href="/#contacts">Контакты</a></nav><div class="header-contact"><a class="phone" data-event="phone_click" href="tel:${company.tel}">${company.phone}</a>${headerMessengers()}</div>${button('Бесплатный замер','/#quiz','button-small header-cta')}<button class="menu-toggle" aria-label="Открыть меню" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span><span></span></button></div><nav id="mobile-menu" class="mobile-menu" aria-label="Мобильная навигация" hidden><a href="/">Главная</a><a href="/#services">Услуги</a><a href="/nashi-raboty/">Наши работы</a><a href="/#prices">Цены</a><a href="/#reviews">Отзывы</a><a href="/#contacts">Контакты</a><div class="mobile-menu-contact"><a class="mobile-menu-phone" data-event="phone_click" href="tel:${company.tel}">${company.phone}</a>${headerMessengers('mobile-menu-messengers')}</div>${button('Рассчитать стоимость','/#quiz')}</nav></header>`;}
export const trust=()=>`<div class="container trust-strip" aria-label="Преимущества ArtBalkon"><div><strong>15 лет</strong><span>опыта команды</span></div><div><strong>1 250+</strong><span>готовых проектов</span></div><div><strong>до 5 лет</strong><span>гарантии по договору</span></div></div>`;
const beforeAfterAsset=file=>file.includes('/')?file:`before-after/${file}`;
const expandServiceBeforeAfter=(service,items,min=12)=>{
 const result=[],seen=new Set(),add=project=>{
  const key=`${beforeAfterAsset(project.before)}|${beforeAfterAsset(project.after)}`;
  if(seen.has(key))return;
  seen.add(key);
  result.push(project);
 };
 items.forEach(add);
 const offset=[...service.slug].reduce((sum,char)=>sum+char.charCodeAt(0),0)%beforeAfterProjects.length;
 for(let index=0;index<beforeAfterProjects.length&&result.length<min;index++)add(beforeAfterProjects[(offset+index)%beforeAfterProjects.length]);
 return result.slice(0,min);
};
const beforeAfterSection=(items=beforeAfterProjects,{serviceTitle=''}={})=>{
 const cards=items.map(p=>{const before=beforeAfterAsset(p.before),after=beforeAfterAsset(p.after),beforeAlt=p.visualized?'до работ, тематическая визуализация':p.beforeReal?'до работ ArtBalkon':'до ремонта, визуальная реконструкция',afterAlt=p.visualized?'после работ, тематическая визуализация':'после работ ArtBalkon';return `<article class="before-after-card reveal"><button class="before-after-compare" type="button" data-comparison data-title="${esc(p.title)}" data-description="${esc(p.description)}" data-before="assets/${before}" data-after="assets/${after}" data-before-real="${Boolean(p.beforeReal)}" data-visualized="${Boolean(p.visualized)}" aria-label="Сравнить до и после: ${esc(p.title)}"><span class="before-after-preview"><span><img src="/assets/${before}" width="960" height="1280" loading="lazy" decoding="async" alt="${esc(p.title)} — ${beforeAlt}"><b>До</b></span><span><img src="/assets/${after}" width="960" height="1280" loading="lazy" decoding="async" alt="${esc(p.title)} — ${afterAlt}"><b>После</b></span></span><span class="before-after-title">${esc(p.title)}</span></button><button class="before-after-lead" type="button" data-application data-project="${esc(p.title)}">Хочу также</button></article>`;}).join('');
 return `<section class="soft-section before-after-section" id="before-after"><div class="section container"><div class="section-heading"><h2>До и После</h2>${serviceTitle?`<p class="section-description">Примеры по услуге «${esc(serviceTitle)}»</p>`:''}</div><div class="before-after-grid ${items.length<3?'compact':''}">${cards}</div></div><dialog class="comparison-modal" id="comparison-modal" aria-labelledby="comparison-title"><div class="comparison-modal-shell"><div class="comparison-modal-head"><div><p class="eyebrow">ПРЕОБРАЖЕНИЕ БАЛКОНА</p><h2 id="comparison-title"></h2><p id="comparison-description"></p></div><button class="comparison-close" type="button" aria-label="Закрыть сравнение">×</button></div><div class="comparison-modal-grid"><figure><span id="comparison-before-label">До · реконструкция</span><img id="comparison-before" width="960" height="1280" alt="Объект до работ"></figure><figure><span id="comparison-after-label">После · ArtBalkon</span><img id="comparison-after" width="960" height="1280" alt="Объект после работ"></figure></div></div></dialog><dialog class="application-modal" id="application-modal" aria-labelledby="application-title"><div class="application-modal-shell"><button class="application-close" type="button" aria-label="Закрыть форму">×</button><div class="application-modal-copy"><p class="eyebrow">ПОНРАВИЛСЯ ПРОЕКТ?</p><h2 id="application-title">Оставить заявку</h2><p>Оставьте контакты — обсудим похожее преображение для вашего балкона.</p><strong id="application-project"></strong></div><form class="contact-form application-form" data-lead-form="transformation" novalidate><input type="hidden" name="project">${contactFields('application-consent')}<p class="form-error" role="alert"></p><button class="button" type="submit">Отправить заявку ${buttonArrow}</button><p class="contact-note">Перезвоним и уточним детали проекта.</p></form></div></dialog></section>`;
};
const processVideoSection=()=>`<section class="soft-section process-video-section" id="video-process"><div class="section container"><div class="section-heading"><div><h2>Видео: процесс работы<br>до и после</h2></div><p class="section-description">Показываем монтаж и готовый результат<br>без постановочных кадров.</p></div><div class="process-video-grid"><article class="process-video-card reveal"><div class="process-video-media"><video controls playsinline preload="metadata" poster="/assets/video/process-poster.jpg"><source src="/assets/video/process-work.mp4" type="video/mp4">Ваш браузер не поддерживает воспроизведение видео.</video></div><div class="process-video-copy"><p class="eyebrow">В ПРОЦЕССЕ РАБОТЫ</p><h3>Монтаж и отделка на объекте</h3><p>Показываем, как мастера выполняют работы и аккуратно собирают будущий интерьер балкона.</p></div></article><article class="process-video-card reveal"><div class="process-video-media"><video controls playsinline preload="metadata" poster="/assets/video/result-poster.jpg"><source src="/assets/video/process-result.mp4" type="video/mp4">Ваш браузер не поддерживает воспроизведение видео.</video></div><div class="process-video-copy"><p class="eyebrow">ГОТОВЫЙ РЕЗУЛЬТАТ</p><h3>Балкон после завершения работ</h3><p>Светлое, чистое и полностью готовое пространство после монтажа и отделки.</p></div></article></div></div></section>`;
const socialSubscribeSection=()=>`<section class="section container social-subscribe" aria-labelledby="social-subscribe-title"><div class="social-subscribe-heading"><p class="eyebrow">ARTBALKON В СОЦИАЛЬНЫХ СЕТЯХ</p><h2 id="social-subscribe-title">Подписывайтесь<br>на наши каналы</h2><p>Свежие работы и идеи, полезные советы, акции и специальные предложения.</p></div><div class="social-subscribe-grid"><article class="social-subscribe-card social-subscribe-telegram reveal"><div class="social-subscribe-visual"><img class="social-subscribe-photo" src="/assets/project-goluboe.webp" width="960" height="640" loading="lazy" decoding="async" alt="Готовая лоджия ArtBalkon"><span class="social-subscribe-icon"><img src="/assets/telegram-logo.svg" width="128" height="128" alt="Логотип Telegram"></span></div><div class="social-subscribe-copy"><div><span>НАШ КАНАЛ</span><h3>Telegram</h3><p>Показываем новые проекты, детали работ и актуальные предложения.</p></div><a class="button" href="${company.channel}" target="_blank" rel="noopener" data-event="telegram_click">Подписаться ${buttonArrow}</a></div></article><article class="social-subscribe-card social-subscribe-vk reveal"><div class="social-subscribe-visual"><img class="social-subscribe-photo" src="/assets/project-khimki.webp" width="960" height="640" loading="lazy" decoding="async" alt="Светлая лоджия после работ ArtBalkon"><span class="social-subscribe-icon"><img src="/assets/vk-logo.svg" width="128" height="128" alt="Логотип ВКонтакте"></span></div><div class="social-subscribe-copy"><div><span>НАША СТРАНИЦА</span><h3>ВКонтакте</h3><p>Сохраняйте идеи, смотрите готовые работы и задавайте вопросы.</p></div><a class="button" href="${company.vk}" target="_blank" rel="noopener">Подписаться ${buttonArrow}</a></div></article></div></section>`;
const advantagesSection=()=>`<section class="soft-section home-advantages" id="about" aria-labelledby="advantages-title"><div class="section container"><div class="home-advantages-heading"><p class="eyebrow">ПОЧЕМУ ARTBALKON</p><h2 id="advantages-title">Преимущества</h2><p>От первого замера до приёмки готового пространства — отвечаем за результат на каждом этапе.</p></div><div class="home-advantages-layout"><div class="home-advantages-list"><article class="is-accent"><span>01</span><div><h3>Квалифицированные мастера</h3><p>Работы выполняют профильные монтажники и отделочники с опытом в балконах и лоджиях.</p></div></article><article><span>02</span><div><h3>Работа по договору</h3><p>Заранее фиксируем состав работ, материалы, стоимость и согласованные сроки.</p></div></article><article><span>03</span><div><h3>Строгий контроль качества</h3><p>Проверяем монтаж, примыкания и отделку. Зимой при комплексных работах используем тепловизор.</p></div></article><article><span>04</span><div><h3>Гарантия до 5 лет</h3><p>Срок и условия гарантии на профили, комплектующие и монтаж закрепляем в договоре.</p></div></article></div><figure class="home-advantages-photo reveal"><img src="/assets/video/process-poster.jpg" width="1280" height="720" loading="lazy" decoding="async" alt="Мастер ArtBalkon выполняет монтаж на объекте"><figcaption><strong>Своя команда мастеров</strong><span>Реальный процесс работы на объекте</span></figcaption></figure></div></div></section>`;
const partnerBrands=[
 ['rehau.png','REHAU','Оконные системы'],
 ['melke.png','Melke','Оконные системы'],
 ['veka.png','VEKA','Оконные системы'],
 ['vek.png','ВЕК','Панели ПВХ'],
 ['cronafloor.png','Cronafloor','Напольные покрытия'],
 ['gealan.png','GEALAN','Оконные системы'],
 ['roto.png','Roto','Оконная фурнитура'],
 ['siegenia.png','SIEGENIA','Оконная фурнитура']
];
const partnerBrandsSection=()=>`<section class="section container partner-brands" aria-labelledby="partner-brands-title"><div class="section-heading partner-brands-heading"><div><p class="eyebrow">ПРОВЕРЕННЫЕ МАТЕРИАЛЫ</p><h2 id="partner-brands-title">Бренды, с которыми<br>мы работаем</h2></div><p class="section-description">Подбираем оконные системы, фурнитуру и отделочные материалы под задачу, бюджет и условия эксплуатации.</p></div><div class="partner-brand-grid">${partnerBrands.map(([image,name,category])=>`<article class="partner-brand-card"><img src="/assets/brands/${image}" width="768" height="280" loading="lazy" decoding="async" alt="${name}"><span>${category}</span></article>`).join('')}</div></section>`;
const reviewsSection=()=>`<section class="soft-section" id="reviews"><div class="section container reviews-live-section"><div class="section-heading"><div><h2>Что говорят наши клиенты</h2></div><p class="section-description">Актуальные оценки и отзывы<br>на независимых площадках.</p></div><div class="reviews-widget-layout"><div class="yandex-reviews-widget"><iframe src="https://yandex.ru/maps-reviews-widget/99931581991?comments" width="100%" height="620" frameborder="0" loading="lazy" title="Отзывы клиентов ArtBalkon на Яндекс Картах"></iframe></div><aside class="reviews-widget-aside"><div><p class="eyebrow">ЯНДЕКС КАРТЫ И АВИТО</p><h3>Отзывы на независимых площадках</h3><p>Свежие отзывы Яндекса отображаются слева. Отзывы и предложения ArtBalkon на Авито доступны в официальном профиле компании.</p></div><div class="reviews-widget-actions"><a class="button button-white" href="${company.reviews}" target="_blank" rel="noopener">Все отзывы на Яндексе ${buttonArrow}</a><a class="button reviews-avito-button" href="${company.avito}" target="_blank" rel="noopener">Отзывы на Авито ${buttonArrow}</a><a class="text-link" href="#quiz">Рассчитать мой балкон ${arrow}</a></div></aside></div></div></section>`;
const finishingStyles=[
 {id:'loft',label:'Лофт',title:'Лофт',text:'Выразительные фактуры кирпича, бетона и металла, тёмные рамы и продуманное направленное освещение.',note:'Подходит для панорамного остекления, кабинета или атмосферной зоны отдыха.',images:['concept-electrics.jpg','concept-roof.jpg','concept-glazing.jpg']},
 {id:'scandi',label:'Сканди',title:'Скандинавский стиль',text:'Светлые оттенки, натуральное дерево и простые формы делают даже небольшой балкон визуально просторнее.',note:'Хороший выбор для спокойного рабочего места и светлой зоны отдыха.',images:['concept-room.jpg','concept-turnkey.jpg','concept-furniture.jpg']},
 {id:'minimal',label:'Минимализм',title:'Минимализм',text:'Чистые линии, встроенное хранение и минимум визуального шума — всё необходимое остаётся на своём месте.',note:'Практичное решение для компактных лоджий и современных интерьеров.',images:['concept-turnkey.jpg','concept-glazing.jpg','concept-room.jpg']},
 {id:'eco',label:'Эко',title:'Экостиль',text:'Дерево, природные оттенки, мягкий свет и живая зелень создают ощущение тёплого пространства рядом с природой.',note:'Подходит для уютной зоны отдыха и спокойного семейного интерьера.',images:['concept-finishing.jpg','concept-furniture.jpg','concept-cottage.jpg']},
 {id:'neoclassic',label:'Неоклассика',title:'Неоклассика',text:'Сдержанная симметрия, качественные материалы и тёплые световые акценты соединяют классику с современным комфортом.',note:'Для лоджии, которая должна стать полноценным продолжением комнаты.',images:['concept-furniture.jpg','concept-room.jpg','concept-turnkey.jpg']}
];
const finishingStylesSection=()=>`<section class="section container finishing-styles" id="finishing-styles" data-finishing-styles aria-labelledby="finishing-styles-title"><div class="section-heading"><div><h2 id="finishing-styles-title">Варианты отделки<br>балконов и лоджий</h2></div><p class="section-description">Показываем разные направления и подбираем материалы под ваш вкус, задачи и бюджет.</p></div><div class="finishing-style-tabs" role="tablist" aria-label="Стили отделки">${finishingStyles.map((style,index)=>`<button type="button" role="tab" id="finishing-tab-${style.id}" aria-controls="finishing-panel-${style.id}" aria-selected="${index===0?'true':'false'}" tabindex="${index===0?'0':'-1'}" data-finishing-tab="${style.id}">${style.label}</button>`).join('')}</div><div class="finishing-style-panels">${finishingStyles.map((style,index)=>`<article class="finishing-style-panel" id="finishing-panel-${style.id}" role="tabpanel" aria-labelledby="finishing-tab-${style.id}" data-finishing-panel="${style.id}" ${index===0?'':'hidden'}><div class="finishing-style-copy"><p class="eyebrow">СТИЛЬ ОТДЕЛКИ</p><h3>${style.title}</h3><p>${style.text}</p><p>${style.note}</p>${button('Подобрать отделку')}</div><div class="finishing-style-gallery">${style.images.map((image,imageIndex)=>`<figure><img src="/assets/${image}" width="960" height="640" loading="lazy" decoding="async" alt="${style.title} — дизайн-концепт отделки балкона${imageIndex+1}"></figure>`).join('')}</div></article>`).join('')}</div></section>`;
export function projectCards(limit=3){return `<div class="project-grid">${projects.slice(0,limit).map(p=>`<article class="project-card"><a class="project-image" data-event="portfolio_open" data-project="${p.slug}" href="/nashi-raboty/${p.slug}/">${pic(p.image,p.alt)}<span class="image-tag">${p.type}</span><span class="image-arrow" aria-hidden="true">↗</span></a><p class="project-location">${p.location}</p><h3><a href="/nashi-raboty/${p.slug}/" data-event="portfolio_open" data-project="${p.slug}">${p.title}</a></h3><p class="project-materials">${p.materials.slice(0,2).join(' · ')}</p><a class="text-link" data-event="portfolio_open" data-project="${p.slug}" href="/nashi-raboty/${p.slug}/">Смотреть проект ${arrow}</a></article>`).join('')}</div>`;}
const sourceServiceDetails={
 'osteklenie-balkonov':{title:'Варианты остекления балкона',intro:'Подбираем оконную систему по назначению балкона, уровню шума, солнечной стороне и требованиям к теплу.',items:[['Холодное остекление','от 7 000 ₽/м² · защита от ветра, осадков и пыли'],['Полутёплое остекление','от 9 000 ₽/м² · больше комфорта без полноценного тёплого контура'],['Тёплое остекление','от 11 000 ₽/м² · для круглогодичного использования'],['Панорамное остекление','от 11 500 ₽/м² · максимум света и открытого вида']],note:'Работаем с профильными системами Melke, Gealan и Rehau, используем фурнитуру Roto и Siegenia. На замере подберём профиль и стеклопакет под ваш балкон.'},
 'osteklenie-lodzhii':{title:'Варианты остекления лоджии',intro:'Учитываем длину проёма, удобство открывания створок, шум с улицы и будущий сценарий использования лоджии.',items:[['Холодное остекление','от 7 000 ₽/м² · для сезонного использования и хранения'],['Полутёплое остекление','от 9 000 ₽/м² · промежуточное решение по теплу'],['Тёплое остекление','от 11 000 ₽/м² · для кабинета или зоны отдыха'],['Панорамное остекление','от 11 500 ₽/м² · больше естественного света']],note:'Используем профили Melke, Gealan и Rehau и фурнитуру Roto и Siegenia. Схему створок и комплектацию согласуем именно для вашей лоджии.'},
 'holodnoe-osteklenie':{title:'Что входит в холодное остекление',intro:'Лёгкая система защищает пространство от дождя, снега, ветра и городской пыли, не перегружая конструкцию.',items:[['Оконная система','от 7 000 ₽/м²'],['Схема створок','Подбираем удобное открывание и доступ для ухода'],['Защита от солнца и шума','Предлагаем подходящее заполнение и конфигурацию'],['Монтаж и примыкания','Герметизируем стыки, устанавливаем отливы и подоконники']],note:'Точная комплектация зависит от геометрии проёма и состояния основания. Все параметры фиксируем после бесплатного замера.'},
 'teploe-osteklenie':{title:'Что входит в тёплое остекление',intro:'Тёплые окна становятся частью единого утеплённого контура и подходят для пространства, которым пользуются круглый год.',items:[['Тёплая система','от 11 000 ₽/м²'],['Профили','Melke, Gealan или Rehau под задачу и бюджет'],['Фурнитура','Roto или Siegenia с удобными режимами открывания'],['Стеклопакет','Подбор по теплу, шуму и расположению объекта']],note:'Одних тёплых окон недостаточно: для комфортной температуры также нужны утепление стен, пола и потолка и согласованный обогрев.'},
 'panoramnoe-osteklenie':{title:'Что учитываем в панорамном остеклении',intro:'Панорамное решение даёт максимум света и современный вид, поэтому особенно важны расчёт конструкции и правильное заполнение.',items:[['Панорамная система','от 11 500 ₽/м²'],['Безопасность','Подбираем надёжные стеклопакеты и профиль'],['Защита от перегрева','Учитываем солнечную сторону и площадь стекла'],['Открывание и уход','Планируем створки так, чтобы ими было удобно пользоваться']],note:'Конструкцию, цвет профиля, стеклопакеты и узлы примыкания согласуем после осмотра объекта и точного замера.'},
 'uteplenie-balkonov':{title:'Как утепляем балкон',intro:'Создаём непрерывный тёплый контур, который уменьшает сквозняки, уличный шум и риск появления конденсата.',items:[['Пеноплекс','от 700 ₽/м² · плотный утеплитель для стен, пола и потолка'],['Пеноплекс и пенофол','Дополнительный отражающий слой и герметизация стыков'],['Пароизоляция','Защита конструкции от влаги и конденсата'],['Контроль качества','Зимой комплексное утепление проверяем тепловизором']],note:'Состав и толщину материалов выбираем с учётом конструкции балкона, остекления и желаемой температуры.'},
 'uteplenie-lodzhii':{title:'Как утепляем лоджию',intro:'Закрываем весь контур без разрывов, сохраняя полезную площадь и заранее учитывая чистовой пол, откосы и мебель.',items:[['Пеноплекс','от 700 ₽/м² · утепление парапета, стен, пола и потолка'],['Пеноплекс и пенофол','Комбинированная схема для дополнительной защиты'],['Пароизоляция','Герметичный слой против влаги и конденсата'],['Контроль качества','Проверка тепловизором при зимних комплексных работах']],note:'Толщину утепления определяем после осмотра лоджии, оценки стен и выбранной оконной системы.'},
 'otdelka-balkonov':{title:'Материалы для отделки балкона',intro:'Подбираем покрытие по температурному режиму, влажности и будущему назначению пространства.',items:[['ПВХ-панели','от 2 500 ₽/м² · практичная и лёгкая отделка'],['Влагостойкий ламинат','от 3 800 ₽/м² · аккуратная поверхность для тёплого балкона'],['Фактуры дерева и кирпича','от 4 500 ₽/м² · выразительный интерьерный акцент'],['Вагонка и стеновой паркет','от 4 000 ₽/м² · натуральная тёплая фактура']],note:'Также выполняем декоративную штукатурку от 6 000 ₽/м² и комбинируем материалы по дизайн-концепции.'},
 'otdelka-lodzhii':{title:'Материалы для отделки лоджии',intro:'Собираем стены, потолок и пол в едином стиле, учитывая утепление лоджии и перепады температуры.',items:[['ПВХ-панели','от 2 500 ₽/м² · неприхотливый вариант'],['Влагостойкий ламинат','от 3 800 ₽/м² · для тёплого интерьерного решения'],['Фактуры дерева и кирпича','от 4 500 ₽/м² · для выразительных акцентов'],['Вагонка и стеновой паркет','от 4 000 ₽/м² · натуральная отделка']],note:'Декоративная штукатурка доступна от 6 000 ₽/м². Образцы и сочетания материалов привезём на замер.'},
 'balkon-pod-klyuch':{title:'Что входит в балкон под ключ',intro:'Одна команда последовательно выполняет все работы — от окон и подготовки основания до света и готового интерьера.',items:[['Остекление','Холодная, тёплая или панорамная система'],['Утепление','Непрерывный контур, пароизоляция и подготовка под обогрев'],['Инженерия','Освещение, выключатели, розетки и интернет-кабель'],['Чистовая отделка','Пол, стены, потолок, откосы и подготовка под мебель']],note:'Состав проекта и итоговую стоимость фиксируем в договоре после замера и выбора материалов.'},
 'lodzhiya-pod-klyuch':{title:'Что входит в лоджию под ключ',intro:'Объединяем остекление, утепление, инженерные работы и отделку в один согласованный проект.',items:[['Остекление','Система и схема створок под длинный проём'],['Утепление','Тёплый контур без мостиков холода'],['Инженерия','Свет, розетки, интернет и подготовка под обогрев'],['Чистовая отделка','Стены, потолок, пол, откосы и места хранения']],note:'До начала работ согласуем материалы, этапы, сроки и единую смету именно для вашей лоджии.'},
 'krysha-nad-balkonom':{title:'Варианты крыши и выноса',intro:'Конструкцию проектируем по состоянию плиты, этажу, фасаду дома и предполагаемым нагрузкам.',items:[['Крыша над балконом','от 8 000 ₽/м²'],['Независимая крыша','Опирается на собственный металлический каркас'],['Зависимая крыша','Связана с конструкцией остекления'],['Остекление с выносом','Позволяет добавить примерно 25–30 см полезного пространства']],note:'Тип каркаса, покрытие, водоотвод и допустимость выноса определяем только после осмотра объекта.'},
 'mebel-dlya-balkona':{title:'Мебель по размерам пространства',intro:'Проектируем встроенные элементы так, чтобы использовать углы, ниши и высоту без потери прохода.',items:[['Шкафы','от 20 000 ₽ · распашные, купе и угловые конструкции'],['Тумбы и стеллажи','Хранение для вещей и хозяйственных принадлежностей'],['Рабочее место','Компьютерный или компактный откидной стол'],['Барная столешница','Узкая зона для отдыха у окна']],note:'Габариты, наполнение, материалы и цвет мебели согласуем после точного замера готового или проектируемого пространства.'},
 'elektrika-na-balkone':{title:'Электрика и освещение',intro:'Заранее планируем точки питания и сценарии света, чтобы проводка была безопасной и не мешала отделке.',items:[['Электромонтаж','от 3 000 ₽'],['Освещение','Люстры, потолочные светильники и локальная подсветка'],['Розетки и выключатели','Расположение под технику, рабочее место и бытовые задачи'],['Интернет-кабель','Скрытая прокладка для кабинета или зоны отдыха']],note:'Количество линий, мощность и способ прокладки определяем по будущей нагрузке и составу отделки.'},
 'obedinenie-balkona-s-komnatoj':{title:'Этапы объединения пространства',intro:'Продумываем новое назначение зоны, геометрию проёма, утепление и обогрев до начала демонтажных и отделочных работ.',items:[['Комплекс работ','от 80 000 ₽'],['Планировка','Замер, консультация и подбор конфигурации, включая широкую столешницу'],['Тепло','Тёплый пол, конвектор или другое согласованное решение'],['Подготовка и отделка','Демонтаж, утепление, инженерия и чистовой интерьер']],note:'Возможность изменения проёма зависит от конструкции дома и требований согласования. Безопасное решение определяем после обследования.'},
 'osteklenie-kottedzhej':{title:'Что остекляем в загородном доме',intro:'Подбираем профиль, стеклопакеты и способ открывания с учётом архитектуры дома и сезонности помещения.',items:[['Комплексное остекление','от 100 000 ₽'],['Окна сложной формы','Арочные, круглые и панорамные конструкции'],['Входные группы','Тёплые двери и большие светопрозрачные проёмы'],['Террасы и веранды','Раздвижные окна и двери, остекление беседок']],note:'Расчёт зависит от размеров проёмов, формы конструкций, выбранного профиля и условий монтажа.'}
};
const sourceServiceDetailsSection=s=>{const detail=sourceServiceDetails[s.slug];if(!detail)return '';return `<section class="section container source-service-details" aria-labelledby="source-service-${esc(s.slug)}"><div class="section-heading"><div><p class="eyebrow">ПОДРОБНО ОБ УСЛУГЕ</p><h2 id="source-service-${esc(s.slug)}">${esc(detail.title)}</h2></div><p class="section-description">${esc(detail.intro)}</p></div><div class="source-service-details-grid">${detail.items.map(([title,text],index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><h3>${esc(title)}</h3><p>${esc(text)}</p></article>`).join('')}</div><div class="source-service-details-note"><p>${esc(detail.note)}</p><p>Цены «от» — ориентиры для планирования. Точную стоимость зафиксируем после замера, выбора материалов и согласования комплектации.</p></div><div class="section-cta">${button('Получить точный расчёт')}</div></section>`;};
const serviceSeoSection=s=>{const seo=serviceSeo[s.slug];if(!seo)return '';return `<section class="section container service-seo-intro"><div><p class="eyebrow">${esc(seo.eyebrow)}</p><h2>${esc(seo.title)}</h2>${seo.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${button('Получить расчёт')}</div><figure><img src="/assets/${esc(seo.concept[0])}" width="960" height="640" loading="lazy" decoding="async" alt="${esc(seo.concept[1])}"><figcaption>${esc(seo.concept[2])} · дизайн-концепт</figcaption></figure></section><section class="soft-section"><div class="section container service-scope"><div class="section-heading"><div><p class="eyebrow">СОСТАВ РАБОТ</p><h2>Что учитываем<br>в проекте</h2></div><p class="section-description">Состав и материалы уточняем после осмотра и точного замера объекта.</p></div><div class="service-scope-grid">${seo.scope.map(([title,text])=>`<article><h3>${esc(title)}</h3><p>${esc(text)}</p></article>`).join('')}</div></div></section><section class="section container service-photo-section"><div class="section-heading"><div><p class="eyebrow">ПРИМЕРЫ РАБОТ</p><h2>Как это выглядит<br>на реальных объектах</h2></div><a class="text-link" href="/nashi-raboty/">Все проекты ${arrow}</a></div><div class="service-photo-grid">${seo.photos.map(([name,alt,caption])=>`<figure>${pic(name,alt)}<figcaption>${esc(caption)}</figcaption></figure>`).join('')}</div></section><section class="section container service-process"><div class="section-heading"><div><p class="eyebrow">ПОЭТАПНО И ПОНЯТНО</p><h2>Как проходит работа</h2></div></div><ol>${seo.steps.map(([title,text])=>`<li><h3>${esc(title)}</h3><p>${esc(text)}</p></li>`).join('')}</ol><div class="section-cta">${button('Начать с бесплатного замера')}</div></section><section class="soft-section"><div class="section container service-page-faq"><div><p class="eyebrow">ВАЖНО ЗНАТЬ</p><h2>Ответы на вопросы</h2><p>Коротко отвечаем на вопросы, которые возникают до замера и расчёта.</p></div><div>${seo.faq.map(([q,a])=>`<details><summary>${esc(q)}<span aria-hidden="true">+</span></summary><p>${esc(a)}</p></details>`).join('')}</div></div></section>`;};
export const consent=id=>`<label class="consent" for="${id}"><input id="${id}" name="consent" type="checkbox" required><span>Соглашаюсь на <a href="/consent/" target="_blank">обработку персональных данных</a> и ознакомлен(а) с <a href="/privacy/" target="_blank">политикой конфиденциальности</a>.</span></label>`;
export const contactFields=id=>`<div class="field-row"><label class="field">Ваше имя<input name="name" autocomplete="given-name" maxlength="70" placeholder="Как к вам обращаться" required></label><label class="field">Телефон<input name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="22" placeholder="+7 (___) ___-__-__" required></label></div><div class="honeypot" aria-hidden="true"><label>Сайт<input name="website" tabindex="-1" autocomplete="off"></label></div>${consent(id)}`;
const quizContext=service=>{
 const mixed={heading:'Узнайте стоимость<br>вашего балкона',progress:'ВАШ БУДУЩИЙ БАЛКОН',objectTitle:'У вас балкон или лоджия?',objectOptions:['Балкон','Лоджия','Не знаю'],serviceOptions:['Холодное остекление','Тёплое остекление','Отделка балкона или лоджии','Утепление балкона или лоджии','Объединение с комнатой']};
 if(!service)return mixed;
 if(service.slug.includes('lodzh'))return {heading:'Узнайте стоимость<br>работ на лоджии',progress:'ВАША БУДУЩАЯ ЛОДЖИЯ',objectTitle:'Какая у вас лоджия?',objectOptions:['Лоджия','Не знаю тип'],serviceOptions:['Холодное остекление лоджии','Тёплое остекление лоджии','Отделка лоджии','Утепление лоджии','Лоджия под ключ']};
 const special={
  'krysha-nad-balkonom':{heading:'Узнайте стоимость<br>крыши над балконом',progress:'КРЫША НАД БАЛКОНОМ',objectTitle:'Какая работа нужна?',objectOptions:['Крыша над балконом','Остекление с выносом','Не знаю'],serviceOptions:['Монтаж крыши над балконом','Сварные работы','Крыша с остеклением','Остекление с выносом']},
  'mebel-dlya-balkona':{heading:'Узнайте стоимость<br>мебели для балкона',progress:'МЕБЕЛЬ ДЛЯ БАЛКОНА',objectTitle:'Что хотите разместить?',objectOptions:['Шкаф или тумбу','Рабочее место','Систему хранения','Не знаю'],serviceOptions:['Встроенная мебель для балкона','Шкаф или тумба','Стеллажи и полки','Рабочий стол']},
  'elektrika-na-balkone':{heading:'Узнайте стоимость<br>электрики на балконе',progress:'ЭЛЕКТРИКА НА БАЛКОНЕ',objectTitle:'Что нужно установить?',objectOptions:['Освещение','Розетки','Свет и розетки','Не знаю'],serviceOptions:['Электрика на балконе','Освещение балкона','Розетки и выключатели','Интернет-кабель']},
  'obedinenie-balkona-s-komnatoj':{heading:'Узнайте стоимость<br>объединения с комнатой',progress:'ОБЪЕДИНЕНИЕ С КОМНАТОЙ',objectTitle:'Что планируете получить?',objectOptions:['Рабочую зону','Зону отдыха','Продолжение кухни','Не знаю'],serviceOptions:['Объединение с комнатой','Утепление перед объединением','Отделка после объединения','Комплекс работ под ключ']},
  'osteklenie-kottedzhej':{heading:'Узнайте стоимость<br>остекления дома',progress:'ОСТЕКЛЕНИЕ ДОМА',objectTitle:'Что требуется остеклить?',objectOptions:['Коттедж или дом','Террасу или веранду','Беседку','Не знаю'],serviceOptions:['Остекление коттеджа или дома','Остекление террасы или веранды','Панорамное остекление','Входная группа']}
 };
 return special[service.slug]||{heading:'Узнайте стоимость<br>работ на балконе',progress:'ВАШ БУДУЩИЙ БАЛКОН',objectTitle:'Какой у вас балкон?',objectOptions:['Балкон','Не знаю тип'],serviceOptions:['Холодное остекление балкона','Тёплое остекление балкона','Отделка балкона','Утепление балкона','Балкон под ключ']};
};
export function quiz(service=null){const context=quizContext(service);const questions=[
 {title:context.objectTitle,name:'object',options:context.objectOptions},
 {title:'Что требуется сделать?',name:'service',options:context.serviceOptions},
 {title:'Когда планируете работы?',name:'timing',options:['Как можно скорее','В течение недели','В течение месяца','Пока интересуюсь']},
 {title:'Выберите подарок',name:'gift',options:['Потолочная сушилка','Светильник и розетки','Тёплый пол']},
 {title:'Куда отправить расчёт?'}
];return `<section class="section container" id="quiz"><div class="quiz-layout"><div class="quiz-intro"><p class="eyebrow">ПОНЯТНАЯ СТОИМОСТЬ</p><h2 id="quiz-title">${context.heading}</h2><p>Ответьте на несколько вопросов — подготовим предварительный расчёт стоимости.</p><div class="quiz-note"><span aria-hidden="true">↗</span><p>Точный расчёт — после бесплатного замера. Учтём размеры, материалы и ваши пожелания.</p></div><a href="tel:${company.tel}" data-event="phone_click" class="quiz-phone">Или просто позвоните<br><strong>${company.phone}</strong></a></div><form class="quiz-form" data-lead-form="quiz" novalidate><div class="quiz-progress-row"><span>${context.progress}</span><span id="step-count">Шаг 1 из 5</span></div><progress id="quiz-progress" value="1" max="5" aria-label="Прогресс расчёта">1 из 5</progress>${questions.map((question,i)=>`<fieldset data-step="${i}" ${i?'hidden':''}><legend tabindex="-1">${question.title}</legend>${i===4?`<p class="step-hint">Менеджер уточнит размеры и детали, затем подготовит предварительную стоимость.</p>${contactFields('quiz-consent')}`:`<div class="quiz-options">${question.options.map(option=>`<label class="quiz-option"><input type="radio" name="${question.name}" value="${option}" required><span>${option}</span><span class="radio-circle" aria-hidden="true"></span></label>`).join('')}</div>`}</fieldset>`).join('')}<p class="form-error" role="alert"></p><div class="quiz-controls"><button type="button" class="back-button" id="quiz-back" disabled>← Назад</button><span class="quiz-duration">Около 1 минуты</span><button type="button" class="quiz-next-button" id="quiz-next">Далее <span aria-hidden="true">→</span></button><button type="submit" class="button" id="quiz-submit" hidden>Получить расчёт ${buttonArrow}</button></div></form></div></section>`;}
const asQuizModal=markup=>markup.replace('<section class="section container" id="quiz"><div class="quiz-layout">','<dialog class="quiz-modal" id="quiz" aria-labelledby="quiz-title"><div class="quiz-modal-shell"><button class="quiz-modal-close" type="button" aria-label="Закрыть расчёт">×</button><div class="quiz-layout">').replace('</form></div></section>','</form></div></div></dialog>');
export function quizModal(service=null){return asQuizModal(quiz(service));}
export function shellWithQuiz(body,options){const pageBody=body.includes('id="quiz"')?asQuizModal(body):body+quizModal();return shell(pageBody,options).replace('/styles.css?v=mobile-menu-1','/styles.css?v=location-headings-1').replace('/app.js?v=comparison-images-1','/app.js?v=context-quiz-1').replace(`<a class="messenger" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Написать в Telegram ${arrow}</a>`,socialIconLinks('final-social-icons')).replace(`<a href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Telegram ↗</a>`,socialIconLinks('footer-social-icons'));}
export const faq=()=>`<section class="section container faq-section" id="faq"><div><p class="eyebrow">ОТВЕТЫ НА ВОПРОСЫ</p><h2>Всё, что важно<br>знать до начала</h2><p class="section-description">Остались вопросы? Расскажем о материалах и поможем выбрать решение.</p><a class="text-link" href="tel:${company.tel}" data-event="phone_click">${company.phone} ${arrow}</a>${button('Получить консультацию')}</div><div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
const certificateFiles=['cert-01.png','cert-02.png','cert-03.jpg','cert-04.jpg','cert-05.jpg','cert-06.jpg','cert-07.jpg','cert-08.png','cert-09.jpg','cert-10.jpg','cert-11.jpg','cert-12.png','cert-13.png','cert-14.png'];
export const certificates=()=>`<section class="certificates-section" id="certificates" data-certificates><div class="section container"><div class="certificates-heading"><div><p class="eyebrow">ДОКУМЕНТЫ И ГАРАНТИИ</p><h2>Сертификаты<br>соответствия</h2><p>Документы на материалы и продукцию, которые используются в проектах ArtBalkon.</p></div><div class="certificate-controls"><span class="certificate-count"><strong data-cert-current>1</strong> / ${certificateFiles.length}</span><button type="button" data-cert-prev aria-label="Предыдущий сертификат">←</button><button type="button" data-cert-next aria-label="Следующий сертификат">→</button></div></div><div class="certificate-track" data-cert-track tabindex="0" role="region" aria-label="Слайдер сертификатов">${certificateFiles.map((file,i)=>`<figure class="certificate-card"><a href="/assets/certificates/${file}" target="_blank" rel="noopener" aria-label="Открыть сертификат ${i+1} крупно"><span class="certificate-paper"><img src="/assets/certificates/${file}" width="566" height="800" loading="lazy" decoding="async" alt="Сертификат соответствия №${i+1} — документ ArtBalkon"></span><figcaption><span>СЕРТИФИКАТ</span><strong>${i+1}</strong></figcaption></a></figure>`).join('')}</div><p class="certificate-hint">Листайте документы стрелками или свайпом. Нажмите на сертификат, чтобы открыть его крупно.</p></div></section>`;
export function contact(){
 const finalCta=`<section class="container final-section final-visual-cta" aria-labelledby="final-cta-title"><div class="final-copy"><p class="eyebrow">БЕСПЛАТНЫЙ ЗАМЕР</p><h2 id="final-cta-title">Оставьте заявку<br>на замер</h2><p>Расскажите, каким хотите видеть свой балкон. Уточним детали, ответим на вопросы и подготовим предварительный расчёт.</p><div class="final-links"><a href="tel:${company.tel}" class="big-phone" data-event="phone_click">${company.phone}</a><a class="messenger" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Написать в Telegram ${arrow}</a></div></div><form class="contact-form final-lead-form" data-lead-form="contact" novalidate><h3>Обсудим ваш проект</h3><p class="final-form-intro">Оставьте контакты — перезвоним и договоримся об удобном времени замера.</p>${contactFields('contact-consent')}<p class="form-error" role="alert"></p><button class="button" type="submit">Отправить заявку ${buttonArrow}</button><p class="contact-note">Ежедневно, с 9:00 до 21:00.</p></form></section>`;
 const contactLocation=`<section class="container contact-location" id="contacts" aria-labelledby="office-title"><div class="contact-location-copy"><p class="eyebrow">ОФИС ARTBALKON</p><h2 id="office-title">Будем рады<br>встрече с вами</h2><p class="contact-location-intro">Обсудим ваш балкон, покажем материалы и ответим на вопросы. Пожалуйста, договоритесь о встрече заранее.</p><div class="contact-location-details"><div class="contact-location-detail"><div><small>Адрес</small><p>${company.address}</p></div></div><div class="contact-location-detail"><div><small>Посещение офиса</small><p>По предварительной записи</p></div></div><div class="contact-location-detail"><div><small>Связаться с нами</small><a href="tel:${company.tel}" data-event="phone_click">${company.phone}</a></div></div></div><div class="contact-location-actions"><div class="contact-socials" aria-label="Социальные сети и мессенджеры"><a class="contact-social" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click"><img src="/assets/telegram-logo.svg" width="128" height="128" alt="Telegram"><span>Telegram</span></a><a class="contact-social" href="${company.max}" target="_blank" rel="noopener"><img src="/assets/max-app-icon.png" width="250" height="250" alt="MAX"><span>MAX</span></a><a class="contact-social" href="${company.vk}" target="_blank" rel="noopener"><img class="contact-social-vk" src="/assets/vk-logo.svg" width="48" height="48" alt="ВКонтакте"><span>ВКонтакте</span></a></div></div></div><div class="contact-map"><iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A39574105600d7e88580935f2a3f26d12b962e6e701aa48792fcf7cf24dae4776&amp;source=constructor" width="100%" height="100%" loading="lazy" title="Офис ArtBalkon на Яндекс Картах" allowfullscreen></iframe><div class="contact-map-label"><strong>ArtBalkon</strong><span>Люберцы · офис 5</span></div></div></section>`;
 return finalCta+contactLocation;
}
export function footer(){return `<footer class="footer"><div class="container footer-grid"><div>${brand}<p>Остекление, утепление и отделка<br>балконов в Москве и Московской области.</p></div><div><p class="footer-title">Что мы делаем</p>${services.slice(0,4).map(s=>`<a href="/${s.slug}/">${s.title}</a>`).join('')}</div><div><p class="footer-title">ArtBalkon</p><a href="/nashi-raboty/">Наши работы</a><a href="/#reviews">Отзывы</a><a href="/#prices">Цены</a><a href="/#contacts">Контакты</a></div><div><a class="phone" href="tel:${company.tel}" data-event="phone_click">${company.phone}</a><p>${company.hours}</p><p>${company.address}<br>Посещение по предварительной записи.</p><a href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Telegram ↗</a></div></div><div class="container footer-bottom"><span>© <span data-year>${new Date().getFullYear()}</span> ArtBalkon</span><a href="/privacy/">Политика конфиденциальности</a><a href="/consent/">Согласие на обработку данных</a><span>Москва и Московская область</span></div></footer>`;}
export function shell(body,{title='Балконы и лоджии под ключ в Москве и Московской области — ArtBalkon',description='Остекление, утепление и внутренняя отделка балконов и лоджий с гарантией по договору.',path='/',noindex=false}={}){const canonical=company.origin+path;const preloadImage=path==='/'?'/assets/hero-balcony-v2.webp':'/assets/project-goluboe.webp';const schema={'@context':'https://schema.org','@type':'HomeAndConstructionBusiness',name:company.name,url:company.origin,telephone:company.tel,address:{'@type':'PostalAddress',addressLocality:'Люберцы',addressRegion:'Московская область',streetAddress:'Октябрьский проспект, 209, офис 5',addressCountry:'RU'},areaServed:['Москва','Московская область'],sameAs:[company.channel,company.reviews]};return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#00777e"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="ArtBalkon"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-light.png" media="(prefers-color-scheme: light)"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-dark.png" media="(prefers-color-scheme: dark)"><link rel="icon" href="/favicon.svg" type="image/svg+xml" sizes="any"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="192x192" href="/apple-touch-icon.png"><link rel="preload" href="/assets/manrope.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="${preloadImage}" as="image" type="image/webp"><link rel="stylesheet" href="/styles.css?v=mobile-menu-1"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script defer src="/app.js?v=comparison-images-1"></script></head><body${path==='/'&&!noindex?' class="home-page"':''}>${header()}<main id="main">${body}</main>${footer()}<button class="scroll-top" id="scroll-top" type="button" aria-label="Вернуться наверх" title="Наверх" hidden>↑</button></body></html>`;}
export function home(){return `<section class="hero container"><div class="hero-content"><p class="eyebrow"><span></span> Остекление, утепление и отделка — от замера до готового интерьера</p><h1>Балконы и лоджии под ключ <span class="location-accent">в Москве и Московской области</span></h1><p class="hero-description">Остекление, утепление и внутренняя отделка балконов и лоджий с гарантией по договору.</p><div class="hero-actions">${button('Рассчитать стоимость')}</div></div><div class="hero-visual hero-slideshow" data-hero-slider><img class="hero-image is-active" src="/assets/hero-balcony-v2.webp" srcset="/assets/hero-balcony-v2-small.webp 960w, /assets/hero-balcony-v2.webp 2048w" sizes="(max-width: 900px) calc(100vw - 40px), 50vw" width="2048" height="1365" loading="eager" fetchpriority="high" decoding="async" alt="Панорамный балкон с зоной отдыха и видом на Москву"><img class="hero-image" src="/assets/glazing-card-warm.jpg" width="960" height="720" loading="lazy" decoding="async" aria-hidden="true" alt="Тёплый балкон с креслом и панорамными окнами"><img class="hero-image" src="/assets/balcony-finishing.jpg" width="1200" height="800" loading="lazy" decoding="async" aria-hidden="true" alt="Балкон с вечерним освещением и отделкой под дерево"><img class="hero-image" src="/assets/before-after/after-01.jpg" width="960" height="640" loading="lazy" decoding="async" aria-hidden="true" alt="Балкон ArtBalkon со светлой отделкой под кирпич"><img class="hero-image" src="/assets/before-after/after-05.jpg" width="960" height="640" loading="lazy" decoding="async" aria-hidden="true" alt="Уютная лоджия ArtBalkon с деревянной отделкой и освещением"><img class="hero-image" src="/assets/before-after/after-11.jpg" width="960" height="640" loading="lazy" decoding="async" aria-hidden="true" alt="Домашний кабинет на лоджии ArtBalkon"></div></section>${trust()}
<section class="section container" id="services"><div class="section-heading services-heading"><div><h2>Услуги</h2><p class="services-subtitle">Что можем сделать с вашим балконом или лоджией</p></div></div><div class="services-grid">${services.slice(0,8).map(s=>`<article class="service-card reveal"><a class="service-card-media" href="/${s.slug}/">${serviceImage(s)}<span class="service-media-icon">${serviceIcon(s.slug)}</span></a><div class="service-card-body"><h3><a href="/${s.slug}/">${s.title}</a></h3><div class="service-card-price"><strong>${money(prices[s.price])}${prices[s.price]===null?'':'/м²'}</strong></div><p>${s.short}</p></div></article>`).join('')}</div></section>
<section class="soft-section"><div class="section container extra-services"><div class="extra-grid">${services.slice(8,13).map(s=>`<article class="extra-card reveal"><a class="extra-card-media" href="/${s.slug}/">${serviceImage(s)}<span class="extra-icon">${serviceIcon(s.slug)}</span></a><div class="extra-card-body"><h3><a href="/${s.slug}/">${s.title}</a></h3><p>${s.short}</p><a href="/${s.slug}/" class="text-link">Подробнее ${arrow}</a></div></article>`).join('')}</div><div class="section-cta">${button('Обсудить мой проект')}</div></div></section>
${beforeAfterSection()}
${processVideoSection()}
${socialSubscribeSection()}
${advantagesSection()}
<section class="soft-section" id="reviews"><div class="section container reviews-live-section"><div class="section-heading"><div><h2>Что говорят наши клиенты</h2></div><p class="section-description">Актуальные оценки и отзывы<br>на независимых площадках.</p></div><div class="reviews-widget-layout"><div class="yandex-reviews-widget"><iframe src="https://yandex.ru/maps-reviews-widget/99931581991?comments" width="100%" height="620" frameborder="0" loading="lazy" title="Отзывы клиентов ArtBalkon на Яндекс Картах"></iframe></div><aside class="reviews-widget-aside"><div><p class="eyebrow">ЯНДЕКС КАРТЫ И АВИТО</p><h3>Отзывы на независимых площадках</h3><p>Свежие отзывы Яндекса отображаются слева. Отзывы и предложения ArtBalkon на Авито доступны в официальном профиле компании.</p></div><div class="reviews-widget-actions"><a class="button button-white" href="${company.reviews}" target="_blank" rel="noopener">Все отзывы на Яндексе ${buttonArrow}</a><a class="button reviews-avito-button" href="${company.avito}" target="_blank" rel="noopener">Отзывы на Авито ${buttonArrow}</a><a class="text-link" href="#quiz">Рассчитать мой балкон ${arrow}</a></div></aside></div></div></section>
${finishingStylesSection()}
<section class="section container" id="glazing"><div class="section-heading"><div><p class="eyebrow">НАЧНЁМ С ОСНОВЫ</p><h2>Какое остекление выбрать</h2></div><p class="section-description">Для сезонного отдыха<br>или комфорта круглый год.</p></div><div class="glazing-grid">${[['cold','Холодное','Для защиты от дождя, ветра, снега и пыли.','holodnoe-osteklenie','ЗАЩИТА ОТ ОСАДКОВ'],['warm','Тёплое','Для балкона, которым можно пользоваться круглый год.','teploe-osteklenie','ТЕПЛО И КОМФОРТ'],['panoramic','Панорамное','Максимум естественного света и современный внешний вид.','panoramnoe-osteklenie','БОЛЬШЕ СВЕТА']].map(([key,title,desc,slug,label])=>`<article class="glazing-card reveal ${key==='warm'?'featured':''}"><span class="card-eyebrow">${label}</span><div class="glazing-card-photo"><img src="/assets/glazing-card-${key}.jpg" width="960" height="720" loading="lazy" decoding="async" alt="${title} остекление балкона"></div><h3>${title} остекление</h3><p>${desc}</p>${key==='warm'?'<span class="glazing-note">Вместе с утеплением и обогревом</span>':'<span class="glazing-note">Подберём решение на замере</span>'}<div class="glazing-price"><strong>${money(prices[key])}<small>/м²</small></strong><a href="/${slug}/" aria-label="Подробнее: ${title.toLowerCase()} остекление">↗</a></div></article>`).join('')}</div><p class="price-disclaimer">Точная стоимость зависит от размеров, профиля, стеклопакета и сложности монтажа.</p><div class="section-cta">${button('Помочь выбрать остекление')}</div></section>
${partnerBrandsSection()}
<section class="soft-section"><div class="section container compare-glazing"><div class="section-heading"><div><p class="eyebrow">ДВА РЕШЕНИЯ — ДВЕ ЗАДАЧИ</p><h2>Холодное или тёплое?</h2></div><p class="section-description">Показываем разницу без сложных терминов.</p></div><div class="choice-grid"><article class="choice-card reveal"><div class="choice-photo"><img src="/assets/glazing-card-cold.jpg" width="960" height="720" loading="lazy" decoding="async" alt="Холодное остекление балкона с алюминиевыми рамами и парапетом"></div><div class="choice-copy"><span>ЗАЩИТА ОТ ПОГОДЫ</span><h3>Холодное остекление</h3><p>Защищает от дождя, снега, ветра и пыли. Подходит для хранения и сезонного использования.</p><a class="text-link" href="/holodnoe-osteklenie/">Подробнее ${arrow}</a></div></article><article class="choice-card reveal"><div class="choice-photo"><img src="/assets/glazing-warm-yandex.jpg" width="1152" height="600" loading="lazy" decoding="async" alt="Тёплая лоджия с рабочим местом — работа ArtBalkon"></div><div class="choice-copy"><span>КОМФОРТ КРУГЛЫЙ ГОД</span><h3>Тёплое остекление</h3><p>Подходит для кабинета, зоны отдыха или продолжения комнаты. Требует утепления всего контура и обогрева.</p><a class="text-link" href="/teploe-osteklenie/">Подробнее ${arrow}</a></div></article></div><div class="section-cta">${button('Помочь выбрать остекление')}</div></div></section>
<section class="section container" id="works"><div class="section-heading"><div><p class="eyebrow">РЕАЛЬНЫЕ ОБЪЕКТЫ. РЕАЛЬНЫЙ РЕЗУЛЬТАТ.</p><h2>Посмотрите, какие балконы<br>мы уже сделали</h2></div>${button('Все наши работы','/nashi-raboty/','button-outline')}</div>${projectCards()}<div class="section-cta">${button('Хочу такой балкон')}</div></section>
${quiz()}
<section class="container thermal-section reveal"><div class="thermal-photo">${pic('thermal','Тепловизор у балконной двери — фотография из раздела контроля качества ArtBalkon')}</div><div class="thermal-copy"><p class="eyebrow">КАЧЕСТВО, КОТОРОЕ МОЖНО ПРОВЕРИТЬ</p><h2>Проверяем качество утепления тепловизором</h2><p>Проверяем конструкцию на теплопотери. Вы увидите результат работы не только визуально, но и на тепловизоре.</p><div class="thermal-condition"><span aria-hidden="true">✳</span><p>Проверка проводится зимой при комплексном остеклении, утеплении и отделке балкона или лоджии.</p></div>${button('Записаться на бесплатный замер')}</div></section>
<section class="section container"><div class="section-heading"><div><p class="eyebrow">ПРОСТО И ПО ПОРЯДКУ</p><h2>От заявки до готового балкона</h2></div></div><ol class="steps">${[['Заявка','Оставляете заявку на сайте или звоните.'],['Замер','Приезжаем на объект и снимаем точные размеры.'],['Расчёт и договор','Согласовываем материалы, стоимость и сроки.'],['Монтаж и отделка','Выполняем работы согласно проекту.'],['Приёмка','Проверяем результат и передаём готовый объект.']].map(([t,p])=>`<li><h3>${t}</h3><p>${p}</p></li>`).join('')}</ol><div class="section-cta">${button('Начать с бесплатного замера')}</div></section>
<section class="section container prices-section" id="prices"><div><p class="eyebrow">ЦЕНЫ БЕЗ ЗАГАДОК</p><h2>Сколько стоит<br>ваш новый балкон</h2><p class="section-description">Ориентиры для планирования бюджета.<br>Точную смету подготовим под ваш объект.</p><p class="prices-question">Хотите узнать стоимость именно вашего балкона?</p>${button('Получить точный расчёт')}</div><div class="price-list">${[['Холодное остекление','cold','holodnoe-osteklenie'],['Тёплое остекление','warm','teploe-osteklenie'],['Панорамное остекление','panoramic','panoramnoe-osteklenie'],['Отделка балкона','finishing','otdelka-balkonov'],['Утепление','insulation','uteplenie-balkonov'],['Балкон под ключ','turnkey','balkon-pod-klyuch']].map(([t,k,s])=>`<a class="price-row" href="/${s}/"><span>${t}</span><strong>${money(prices[k])}${prices[k]===null?'':'<small>/м²</small>'}</strong><span aria-hidden="true">↗</span></a>`).join('')}<p class="price-disclaimer">Цены «от» зависят от выбранных материалов и объёма работ. Для утепления и отделки учитывается площадь обрабатываемых поверхностей.</p></div></section>
${faq()}${certificates()}${contact()}`;}
export function servicePage(s){return `<section class="container landing-hero"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><span>${s.title}</span></nav><div class="landing-grid"><div><h1>${headingWithLocation(s.h1)}</h1><p class="hero-description">${s.offer}</p><p class="landing-price">${money(prices[s.price])}${prices[s.price]===null?'':' <small>/м²</small>'}</p>${button('Рассчитать стоимость','#quiz')}<p class="hero-note">Бесплатный замер · Москва и Московская область</p></div><div class="landing-photo">${pic(s.image,s.title+' — фотография из портфолио ArtBalkon','',true)}</div></div></section><section class="section container"><div class="section-heading"><h2>${s.question}</h2><p class="section-description">${s.answer}</p></div><div class="feature-list">${s.features.map(f=>`<div><h3>${f}</h3></div>`).join('')}</div></section>${s.slug==='osteklenie-balkonov'?`<section class="container related-services"><h2>Три решения для разных задач</h2>${services.filter(v=>['holodnoe-osteklenie','teploe-osteklenie','panoramnoe-osteklenie'].includes(v.slug)).map(v=>`<a class="price-row" href="/${v.slug}/"><span>${v.title}</span><strong>${money(prices[v.price])}/м²</strong>${arrow}</a>`).join('')}</section>`:''}<section class="section container"><div class="section-heading"><h2>Как это выглядит<br>в готовых проектах</h2><a class="text-link" href="/nashi-raboty/">Все работы ${arrow}</a></div>${projectCards()}</section>${quiz(s)}${contact()}`;}
export function servicePageWithSeo(s){const projectStart='<section class="section container"><div class="section-heading"><h2>Как это выглядит<br>в готовых проектах</h2>';const themed=sourceServiceDetailsSection(s)+serviceSeoSection(s).replace('Как проходит работа','От заявки до готового результата');const serviceProjects=expandServiceBeforeAfter(s,serviceBeforeAfterProjects[s.slug]||[]);const openingSections=`${beforeAfterSection(serviceProjects,{serviceTitle:s.title})}${reviewsSection()}${trust()}`;const scopedQuiz=quiz(s);const page=servicePage(s).replace('</div></section>','</div></section>'+openingSections).replace(projectStart,themed+projectStart);return page.replace(scopedQuiz,`${partnerBrandsSection()}${certificates()}${scopedQuiz}`);}
export function projectPage(p){return `<section class="container case-intro"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/nashi-raboty/">Наши работы</a><span>/</span><span>${p.title}</span></nav><p class="eyebrow">${p.location}</p><h1>${p.title}</h1><p class="hero-description">${p.intro}</p><div class="case-layout"><div class="case-photo">${pic(p.image,p.alt,'',true)}</div><div class="case-details"><span class="tag">${p.type}</span><h2>Что сделали</h2><ul class="check-list">${p.works.map(w=>`<li>${w}</li>`).join('')}</ul><h2>Материалы</h2><ul>${p.materials.map(m=>`<li>${m}</li>`).join('')}</ul><p class="case-meta">Срок и итоговая стоимость этого объекта не опубликованы.</p>${button('Рассчитать похожий проект','/#quiz')}<a class="source-link" href="${p.source}" target="_blank" rel="noopener">Объект на сайте ArtBalkon ↗</a></div></div></section>${contact()}`;}
