import {company,prices,projects,services,faqs,integrations} from './content.mjs';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=v=>v===null?'По проекту':`от ${v.toLocaleString('ru-RU')} ₽`;
export const arrow='<span aria-hidden="true">↗</span>';
const iconPaths={
 'osteklenie-balkonov':'<rect x="3" y="3" width="18" height="18" rx="1"/><path d="M12 3v18M3 12h18"/>',
 'uteplenie-balkonov':'<path d="M4 5h16v14H4zM8 5v14M16 5v14M4 10h16M4 14h16"/>',
 'otdelka-balkonov':'<path d="M4 19V5h16v14M8 5v14M16 5v14M4 12h16"/>',
 'balkon-pod-klyuch':'<path d="m3 11 9-7 9 7M5 10v10h14V10M9 20v-6h6v6"/>',
 'krysha-nad-balkonom':'<path d="m3 11 9-7 9 7M5 11h14M7 11v9M17 11v9M5 20h14"/>',
 'mebel-dlya-balkona':'<path d="M5 4h14v16H5zM5 11h14M9 7h2M9 15h2"/>',
 'elektrika-na-balkone':'<path d="M13 2 6 13h6l-1 9 7-12h-6l1-8Z"/>',
 'obedinenie-balkona-s-komnatoj':'<path d="M3 4h7v16H3zM14 4h7v16h-7zM10 12h4M8 10l2 2-2 2M16 10l-2 2 2 2"/>',
 'osteklenie-kottedzhej':'<path d="m3 11 9-7 9 7v9H3zM8 20v-6h8v6M6 11h12"/>'
};
export const serviceIcon=slug=>`<svg class="service-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${iconPaths[slug]||iconPaths['balkon-pod-klyuch']}</svg>`;
const serviceVisuals={
 'osteklenie-balkonov':['card-glazing','Современное панорамное остекление балкона с видом на Москву'],
 'uteplenie-balkonov':['card-insulation','Аккуратно утеплённые стены, пол и потолок балкона'],
 'otdelka-balkonov':['card-finishing','Готовая отделка балкона деревом с продуманным освещением'],
 'balkon-pod-klyuch':['card-turnkey','Готовый балкон под ключ с рабочей зоной и местом для отдыха'],
 'krysha-nad-balkonom':['card-roof','Новая надёжная крыша над остеклённым балконом'],
 'mebel-dlya-balkona':['card-furniture','Встроенный шкаф, скамья и компактный стол на балконе'],
 'elektrika-na-balkone':['card-electrics','Тёплое освещение и электрические точки на готовом балконе'],
 'obedinenie-balkona-s-komnatoj':['card-room','Светлая гостиная, объединённая с утеплённой лоджией'],
 'osteklenie-kottedzhej':['card-cottage','Панорамное остекление веранды загородного дома']
};
const serviceImage=s=>{const [name,alt]=serviceVisuals[s.slug];return `<img src="/assets/${name}.webp" width="960" height="640" loading="lazy" decoding="async" alt="${esc(alt)}">`;};
export const button=(label,href='#quiz',extra='')=>`<a class="button ${extra}" href="${href}">${label} ${arrow}</a>`;
export function pic(name,alt,classes='',eager=false){return `<img class="${classes}" src="/assets/${name}.webp" srcset="/assets/${name}-small.webp 480w, /assets/${name}.webp 1000w" sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1000px) 50vw, 600px" width="1000" height="1100" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async" alt="${esc(alt)}">`;}
export const brand=`<a class="brand" href="/" aria-label="ArtBalkon — главная"><img class="brand-logo" src="/assets/artbalkon-logo.svg" width="461" height="132" alt="ArtBalkon"></a>`;
const headerMessengers=extra=>`<div class="header-messengers ${extra||''}" aria-label="Написать в мессенджер"><a class="header-messenger telegram-messenger" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click" aria-label="Написать в Telegram"><img src="/assets/telegram-logo.svg" width="128" height="128" alt="Telegram"></a><a class="header-messenger max-messenger" href="${company.max}" target="_blank" rel="noopener" aria-label="Написать в MAX"><img src="/assets/max-app-icon.png" width="250" height="250" alt="MAX"></a></div>`;
export function header(){return `<a class="skip-link" href="#main">Перейти к содержанию</a><header class="site-header"><div class="container header-inner">${brand}<nav class="desktop-nav" aria-label="Основная навигация"><a href="/#services">Услуги</a><a href="/nashi-raboty/">Наши работы</a><a href="/#prices">Цены</a><a href="/#reviews">Отзывы</a><a href="/#contacts">Контакты</a></nav><div class="header-contact"><a class="phone" data-event="phone_click" href="tel:${company.tel}">${company.phone}</a>${headerMessengers()}</div>${button('Бесплатный замер','/#quiz','button-small header-cta')}<button class="menu-toggle" aria-label="Открыть меню" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></div><nav id="mobile-menu" class="mobile-menu" aria-label="Мобильная навигация" hidden><a href="/#services">Услуги</a><a href="/nashi-raboty/">Наши работы</a><a href="/#prices">Цены</a><a href="/#reviews">Отзывы</a><a href="/#contacts">Контакты</a>${button('Рассчитать стоимость','/#quiz')}</nav></header>`;}
export const trust=()=>`<div class="hero-trust" aria-label="Преимущества ArtBalkon"><div><strong>15 лет</strong><span>опыта команды</span></div><div><strong>1 250+</strong><span>готовых проектов</span></div><div><strong>до 5 лет</strong><span>гарантии по договору</span></div></div>`;
export function projectCards(limit=3){return `<div class="project-grid">${projects.slice(0,limit).map(p=>`<article class="project-card"><a class="project-image" data-event="portfolio_open" data-project="${p.slug}" href="/nashi-raboty/${p.slug}/">${pic(p.image,p.alt)}<span class="image-tag">${p.type}</span><span class="image-arrow" aria-hidden="true">↗</span></a><p class="project-location">${p.location}</p><h3><a href="/nashi-raboty/${p.slug}/" data-event="portfolio_open" data-project="${p.slug}">${p.title}</a></h3><p class="project-materials">${p.materials.slice(0,2).join(' · ')}</p><a class="text-link" data-event="portfolio_open" data-project="${p.slug}" href="/nashi-raboty/${p.slug}/">Смотреть проект ${arrow}</a></article>`).join('')}</div>`;}
export const consent=id=>`<label class="consent" for="${id}"><input id="${id}" name="consent" type="checkbox" required><span>Соглашаюсь на <a href="/consent/" target="_blank">обработку персональных данных</a> и ознакомлен(а) с <a href="/privacy/" target="_blank">политикой конфиденциальности</a>.</span></label>`;
export const contactFields=id=>`<div class="field-row"><label class="field">Ваше имя<input name="name" autocomplete="given-name" maxlength="70" placeholder="Как к вам обращаться" required></label><label class="field">Телефон<input name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="22" placeholder="+7 (___) ___-__-__" required></label></div><div class="honeypot" aria-hidden="true"><label>Сайт<input name="website" tabindex="-1" autocomplete="off"></label></div>${consent(id)}`;
export function quiz(){let options=[['Остекление','Утепление','Отделка','Балкон под ключ'],['Балкон','Лоджия','Панорамный балкон','Другое'],[],['Как можно скорее','В течение месяца','Через 2–3 месяца','Пока выбираю']];return `<section class="section container" id="quiz"><div class="quiz-layout"><div class="quiz-intro"><p class="eyebrow">ПОНЯТНАЯ СТОИМОСТЬ</p><h2>Узнайте стоимость<br>вашего балкона</h2><p>Ответьте на несколько вопросов — подготовим предварительный расчёт стоимости.</p><div class="quiz-note"><span aria-hidden="true">↗</span><p>Точный расчёт — после бесплатного замера. Учтём размеры, материалы и ваши пожелания.</p></div><a href="tel:${company.tel}" data-event="phone_click" class="quiz-phone">Или просто позвоните<br><strong>${company.phone}</strong></a></div><form class="quiz-form" data-lead-form="quiz" novalidate><div class="quiz-progress-row"><span>ВАШ БУДУЩИЙ БАЛКОН</span><span id="step-count">Шаг 1 из 5</span></div><progress id="quiz-progress" value="1" max="5" aria-label="Прогресс расчёта">1 из 5</progress>${['Что нужно сделать?','Какой у вас объект?','Какой примерный размер?','Когда планируете работы?','Куда отправить расчёт?'].map((q,i)=>`<fieldset data-step="${i}" ${i?'hidden':''}><legend tabindex="-1">${q}</legend>${i===2?`<p class="step-hint">Укажите длину остекления или количество створок. Если не знаете — так и напишите.</p><label class="field">Размер или количество створок<input name="size" maxlength="100" placeholder="Например, 3 метра или 4 створки" required></label>`:i===4?`<p class="step-hint">Уточним детали и подготовим предварительную стоимость.</p>${contactFields('quiz-consent')}`:`<div class="quiz-options">${options[i].map((o,j)=>`<label class="quiz-option"><input type="radio" name="${['service','object','','timing'][i]}" value="${o}" required><span class="option-number">0${j+1}</span><span>${o}</span><span class="radio-circle" aria-hidden="true"></span></label>`).join('')}</div>`}</fieldset>`).join('')}<p class="form-error" role="alert"></p><div class="quiz-controls"><button type="button" class="back-button" id="quiz-back" disabled>← Назад</button><span class="quiz-duration">Около 1 минуты</span><button type="button" class="button" id="quiz-next">Далее ${arrow}</button><button type="submit" class="button" id="quiz-submit" hidden>Получить расчёт ${arrow}</button></div></form></div></section>`;}
export const faq=()=>`<section class="section container faq-section" id="faq"><div><p class="eyebrow">ОТВЕТЫ НА ВОПРОСЫ</p><h2>Всё, что важно<br>знать до начала</h2><p class="section-description">Остались вопросы? Расскажем о материалах и поможем выбрать решение.</p><a class="text-link" href="tel:${company.tel}" data-event="phone_click">${company.phone} ${arrow}</a>${button('Получить консультацию')}</div><div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
export function contact(){return `<section class="container final-section" id="contacts"><div class="final-copy"><p class="eyebrow">НАЧНЁМ С ВАШЕЙ ИДЕИ</p><h2>Рассчитаем стоимость<br>вашего балкона</h2><p>Оставьте номер телефона — уточним задачу и подготовим предварительный расчёт.</p><div class="final-links"><a href="tel:${company.tel}" class="big-phone" data-event="phone_click">${company.phone}</a><a class="messenger" href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Написать в Telegram ${arrow}</a></div></div><form class="contact-form" data-lead-form="contact" novalidate>${contactFields('contact-consent')}<p class="form-error" role="alert"></p><button class="button" type="submit">Получить расчёт ${arrow}</button><p class="contact-note">Замерщики работают ежедневно, с 9:00 до 21:00.</p></form></section>`;}
export function footer(){return `<footer class="footer"><div class="container footer-grid"><div>${brand}<p>Остекление, утепление и отделка<br>балконов в Москве и МО.</p></div><div><p class="footer-title">Что мы делаем</p>${services.slice(0,4).map(s=>`<a href="/${s.slug}/">${s.title}</a>`).join('')}</div><div><p class="footer-title">ArtBalkon</p><a href="/nashi-raboty/">Наши работы</a><a href="/#reviews">Отзывы</a><a href="/#prices">Цены</a><a href="/#contacts">Контакты</a></div><div><a class="phone" href="tel:${company.tel}" data-event="phone_click">${company.phone}</a><p>${company.hours}</p><p>${company.address}<br>Посещение по предварительной записи.</p><a href="${company.telegram}" target="_blank" rel="noopener" data-event="telegram_click">Telegram ↗</a></div></div><div class="container footer-bottom"><span>© <span data-year>${new Date().getFullYear()}</span> ArtBalkon</span><a href="/privacy/">Политика конфиденциальности</a><a href="/consent/">Согласие на обработку данных</a><span>Москва и Московская область</span></div></footer><div class="mobile-bottom"><a href="tel:${company.tel}" data-event="phone_click">Позвонить</a><a href="/#quiz">Рассчитать стоимость ↗</a></div>`;}
export function shell(body,{title='Остекление и отделка балконов под ключ в Москве и МО — ArtBalkon',description='Остекление, утепление и отделка балконов в Москве и Московской области. Реальные работы, понятные цены, бесплатный замер. Гарантия до 5 лет по договору.',path='/',noindex=false}={}){const canonical=company.origin+path;const schema={'@context':'https://schema.org','@type':'HomeAndConstructionBusiness',name:company.name,url:company.origin,telephone:company.tel,address:{'@type':'PostalAddress',addressLocality:'Люберцы',addressRegion:'Московская область',streetAddress:'Октябрьский проспект, 209, офис 5',addressCountry:'RU'},areaServed:['Москва','Московская область'],sameAs:[company.channel,company.reviews]};return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#00777e"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="ArtBalkon"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/manrope.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="/assets/after.webp" as="image" type="image/webp"><link rel="stylesheet" href="/styles.css?v=hero-usp-1"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script defer src="/app.js"></script></head><body${path==='/'&&!noindex?' class="home-page"':''}>${header()}<main id="main">${body}</main>${footer()}</body></html>`;}
export function home(){return `<section class="hero hero-full"><picture class="hero-backdrop"><source media="(max-width:640px)" srcset="/assets/hero-balcony-v2-small.webp"><img src="/assets/hero-balcony-v2.webp" width="1942" height="809" loading="eager" fetchpriority="high" decoding="async" alt="Современный тёплый балкон с панорамным остеклением и видом на Москву"></picture><div class="container hero-full-inner"><div class="hero-content"><p class="eyebrow"><span></span> БАЛКОН, В КОТОРОМ ХОЧЕТСЯ ЖИТЬ</p><h1>Остекление и&nbsp;отделка балконов <em>под ключ</em> в&nbsp;Москве и&nbsp;МО</h1><p class="hero-description">Создаём тёплые, светлые и продуманные пространства — от новых окон до готового интерьера.</p><div class="hero-offer"><span>Холодное остекление</span><strong>от 7 000 ₽/м²</strong></div><div class="hero-actions">${button('Рассчитать стоимость')}${button('Посмотреть работы','#works','button-outline')}</div>${trust()}</div></div><span class="hero-concept-label">КОНЦЕПЦИЯ ПРОСТРАНСТВА ARTBALKON</span></section>
<section class="section container" id="services"><div class="section-heading"><div><p class="eyebrow">ОТ ОКОН ДО ГОТОВОГО ИНТЕРЬЕРА</p><h2>Что можем сделать<br>с вашим балконом</h2></div><p class="section-description">Выберите отдельную услугу<br>или доверьте нам весь проект.</p></div><div class="services-grid">${services.slice(0,4).map((s,i)=>`<article class="service-card reveal"><a class="service-card-media" href="/${s.slug}/">${serviceImage(s)}<span class="service-number">0${i+1}</span><span class="service-media-icon">${serviceIcon(s.slug)}</span></a><div class="service-card-body"><h3><a href="/${s.slug}/">${s.title}</a></h3><p>${s.short}</p><a href="/${s.slug}/" class="text-link">Подробнее ${arrow}</a></div></article>`).join('')}</div><div class="section-cta">${button('Рассчитать стоимость работ')}</div></section>
<section class="soft-section"><div class="section container extra-services"><div class="section-heading"><div><p class="eyebrow">БОЛЬШЕ ВОЗМОЖНОСТЕЙ</p><h2>Больше возможностей<br>для вашего балкона</h2></div><p class="section-description">От отдельных работ до полного<br>переустройства пространства.</p></div><div class="extra-grid">${services.slice(4,9).map(s=>`<article class="extra-card reveal"><a class="extra-card-media" href="/${s.slug}/">${serviceImage(s)}<span class="extra-icon">${serviceIcon(s.slug)}</span></a><div class="extra-card-body"><h3><a href="/${s.slug}/">${s.title}</a></h3><p>${s.short}</p><a href="/${s.slug}/" class="text-link">Подробнее ${arrow}</a></div></article>`).join('')}</div><div class="section-cta">${button('Обсудить мой проект')}</div></div></section>
<section class="section container" id="glazing"><div class="section-heading"><div><p class="eyebrow">НАЧНЁМ С ОСНОВЫ</p><h2>Какое остекление выбрать</h2></div><p class="section-description">Для сезонного отдыха<br>или комфорта круглый год.</p></div><div class="glazing-grid">${[['cold','Холодное','Для защиты от дождя, ветра, снега и пыли.','holodnoe-osteklenie','01 / ЗАЩИТА ОТ ОСАДКОВ'],['warm','Тёплое','Для балкона, которым можно пользоваться круглый год.','teploe-osteklenie','02 / ТЕПЛО И КОМФОРТ'],['panoramic','Панорамное','Максимум естественного света и современный внешний вид.','panoramnoe-osteklenie','03 / БОЛЬШЕ СВЕТА']].map(([key,title,desc,slug,label])=>`<article class="glazing-card reveal ${key==='warm'?'featured':''}"><span class="card-eyebrow">${label}</span><div class="window-diagram ${key}" aria-hidden="true"><i></i><i></i><i></i></div><h3>${title} остекление</h3><p>${desc}</p>${key==='warm'?'<span class="glazing-note">Вместе с утеплением и обогревом</span>':'<span class="glazing-note">Подберём решение на замере</span>'}<div class="glazing-price"><strong>${money(prices[key])}<small>/м²</small></strong><a href="/${slug}/" aria-label="Подробнее: ${title.toLowerCase()} остекление">↗</a></div></article>`).join('')}</div><p class="price-disclaimer">Точная стоимость зависит от размеров, профиля, стеклопакета и сложности монтажа.</p><div class="section-cta">${button('Помочь выбрать остекление')}</div></section>
<section class="soft-section"><div class="section container compare-glazing"><div class="section-heading"><div><p class="eyebrow">ДВА РЕШЕНИЯ — ДВЕ ЗАДАЧИ</p><h2>Тёплое или холодное?</h2></div><p class="section-description">Показываем разницу без сложных терминов.</p></div><div class="choice-grid"><article class="choice-card reveal"><div class="choice-photo">${pic('project-moscow','Тёплая утеплённая лоджия с отделкой')}</div><div class="choice-copy"><span>КОМФОРТ КРУГЛЫЙ ГОД</span><h3>Тёплое остекление</h3><p>Подходит для кабинета, зоны отдыха или продолжения комнаты. Требует утепления всего контура и обогрева.</p><a class="text-link" href="/teploe-osteklenie/">Подробнее ${arrow}</a></div></article><article class="choice-card reveal"><div class="choice-photo">${pic('after','Практичный остеклённый балкон')}</div><div class="choice-copy"><span>ЗАЩИТА ОТ ПОГОДЫ</span><h3>Холодное остекление</h3><p>Защищает от дождя, снега, ветра и пыли. Подходит для хранения и сезонного использования.</p><a class="text-link" href="/holodnoe-osteklenie/">Подробнее ${arrow}</a></div></article></div><div class="section-cta">${button('Помочь выбрать остекление')}</div></div></section>
<section class="section container" id="works"><div class="section-heading"><div><p class="eyebrow">РЕАЛЬНЫЕ ОБЪЕКТЫ. РЕАЛЬНЫЙ РЕЗУЛЬТАТ.</p><h2>Посмотрите, какие балконы<br>мы уже сделали</h2></div>${button('Все наши работы','/nashi-raboty/','button-outline')}</div>${projectCards()}<div class="section-cta">${button('Хочу такой балкон')}</div><div class="transformation reveal"><div class="transformation-copy"><p class="eyebrow">ОТ ЧЕРНОВЫХ РАБОТ К УЮТУ</p><h3>Разница,<br>которую видно</h3><p>За красивой отделкой — утепление, подготовка основания и внимание к деталям.</p><a href="#quiz" class="text-link">Хочу такой результат ${arrow}</a></div><figure>${pic('before','Балкон в процессе утепления плитами Пеноплэкс')}<figcaption>ДО · В ПРОЦЕССЕ УТЕПЛЕНИЯ</figcaption></figure><figure>${pic('after','Тот же балкон после отделки, фотография с сайта ArtBalkon')}<figcaption>ПОСЛЕ · ГОТОВЫЙ БАЛКОН</figcaption></figure></div></section>
${quiz()}
<section class="section container why-section" id="about"><div class="section-heading"><div><p class="eyebrow">ПОЧЕМУ ARTBALKON</p><h2>За результат<br>отвечаем сами</h2></div><p class="section-description">От выбора материалов до приёмки.<br>Внимание к вашему дому на каждом этапе.</p></div><div class="why-grid">${[['01','Работаем по договору','Стоимость, сроки и объём работ согласовываем до начала.'],['02','Гарантия до 5 лет','На профили, комплектующие и монтаж. Срок и условия для вашего заказа — в договоре.'],['03','Проверяем тепловизором','Зимой при комплексном остеклении, утеплении и отделке.'],['04','Реальные работы','Показываем выполненные объекты и материалы, которые использовали.']].map(([n,t,d])=>`<article><span class="why-number">${n}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
<section class="container thermal-section reveal"><div class="thermal-photo">${pic('thermal','Тепловизор у балконной двери — фотография из раздела контроля качества ArtBalkon')}</div><div class="thermal-copy"><p class="eyebrow">КАЧЕСТВО, КОТОРОЕ МОЖНО ПРОВЕРИТЬ</p><h2>Проверяем качество утепления тепловизором</h2><p>Проверяем конструкцию на теплопотери. Вы увидите результат работы не только визуально, но и на тепловизоре.</p><div class="thermal-condition"><span aria-hidden="true">✳</span><p>Проверка проводится зимой при комплексном остеклении, утеплении и отделке балкона или лоджии.</p></div>${button('Записаться на бесплатный замер')}</div></section>
<section class="section container"><div class="section-heading"><div><p class="eyebrow">ПРОСТО И ПО ПОРЯДКУ</p><h2>От заявки до готового балкона</h2></div></div><ol class="steps">${[['Заявка','Оставляете заявку на сайте или звоните.'],['Замер','Приезжаем на объект и снимаем точные размеры.'],['Расчёт и договор','Согласовываем материалы, стоимость и сроки.'],['Монтаж и отделка','Выполняем работы согласно проекту.'],['Приёмка','Проверяем результат и передаём готовый объект.']].map(([t,p],i)=>`<li><span>0${i+1}</span><h3>${t}</h3><p>${p}</p></li>`).join('')}</ol><div class="section-cta">${button('Начать с бесплатного замера')}</div></section>
<section class="soft-section" id="reviews"><div class="section container"><div class="section-heading"><div><p class="eyebrow">СЛОВО НАШИМ КЛИЕНТАМ</p><h2>Что говорят наши клиенты</h2></div><a class="button button-white" href="${company.reviews}" target="_blank" rel="noopener">Все отзывы на Яндексе ${arrow}</a></div><div class="review-grid">${['Заказали отделку небольшой лоджии. Результат отличный, сделали очень аккуратно и в срок.','Благодарю компанию "АртБалкон" за проделанную работу ! Балкон-хламовник, на который страшно зайти было превратили в уютное место :-)','Компания показала себя хорошо👍 Всё точно в срок, сделали хорошо. Абсолютно всё, как договаривались.'].map(text=>`<figure class="review"><span class="review-quote" aria-hidden="true">“</span><blockquote>${esc(text)}</blockquote><figcaption>Фрагмент отзыва с сайта ArtBalkon</figcaption></figure>`).join('')}</div><p class="review-note">Отзывы опубликованы на действующем сайте компании. Полные отзывы доступны на Яндексе.</p><div class="review-actions">${button('Рассчитать мой балкон')}<a class="text-link" href="${company.reviews}" target="_blank" rel="noopener">Все отзывы на Яндексе ${arrow}</a></div></div></section>
<section class="section container prices-section" id="prices"><div><p class="eyebrow">ЦЕНЫ БЕЗ ЗАГАДОК</p><h2>Сколько стоит<br>ваш новый балкон</h2><p class="section-description">Ориентиры для планирования бюджета.<br>Точную смету подготовим под ваш объект.</p><p class="prices-question">Хотите узнать стоимость именно вашего балкона?</p>${button('Получить точный расчёт')}</div><div class="price-list">${[['Холодное остекление','cold','holodnoe-osteklenie'],['Тёплое остекление','warm','teploe-osteklenie'],['Панорамное остекление','panoramic','panoramnoe-osteklenie'],['Отделка балкона','finishing','otdelka-balkonov'],['Утепление','insulation','uteplenie-balkonov'],['Балкон под ключ','turnkey','balkon-pod-klyuch']].map(([t,k,s])=>`<a class="price-row" href="/${s}/"><span>${t}</span><strong>${money(prices[k])}${prices[k]===null?'':'<small>/м²</small>'}</strong><span aria-hidden="true">↗</span></a>`).join('')}<p class="price-disclaimer">Цены «от» зависят от выбранных материалов и объёма работ. Для утепления и отделки учитывается площадь обрабатываемых поверхностей.</p></div></section>
${faq()}${contact()}`;}
export function servicePage(s){return `<section class="container landing-hero"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><span>${s.title}</span></nav><div class="landing-grid"><div><p class="eyebrow">${s.label}</p><h1>${s.h1}</h1><p class="hero-description">${s.offer}</p><p class="landing-price">${money(prices[s.price])}${prices[s.price]===null?'':' <small>/м²</small>'}</p>${button('Рассчитать стоимость','#quiz')}<p class="hero-note">Бесплатный замер · Москва и Московская область</p></div><div class="landing-photo">${pic(s.image,s.title+' — фотография из портфолио ArtBalkon','',true)}</div></div></section><section class="section container"><div class="section-heading"><h2>${s.question}</h2><p class="section-description">${s.answer}</p></div><div class="feature-list">${s.features.map((f,i)=>`<div><span>0${i+1}</span><h3>${f}</h3></div>`).join('')}</div></section>${s.slug==='osteklenie-balkonov'?`<section class="container related-services"><h2>Три решения для разных задач</h2>${services.filter(v=>['holodnoe-osteklenie','teploe-osteklenie','panoramnoe-osteklenie'].includes(v.slug)).map(v=>`<a class="price-row" href="/${v.slug}/"><span>${v.title}</span><strong>${money(prices[v.price])}/м²</strong>${arrow}</a>`).join('')}</section>`:''}<section class="section container"><div class="section-heading"><h2>Как это выглядит<br>в готовых проектах</h2><a class="text-link" href="/nashi-raboty/">Все работы ${arrow}</a></div>${projectCards()}</section>${quiz()}${contact()}`;}
export function projectPage(p){return `<section class="container case-intro"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/nashi-raboty/">Наши работы</a><span>/</span><span>${p.title}</span></nav><p class="eyebrow">${p.location}</p><h1>${p.title}</h1><p class="hero-description">${p.intro}</p><div class="case-layout"><div class="case-photo">${pic(p.image,p.alt,'',true)}</div><div class="case-details"><span class="tag">${p.type}</span><h2>Что сделали</h2><ul class="check-list">${p.works.map(w=>`<li>${w}</li>`).join('')}</ul><h2>Материалы</h2><ul>${p.materials.map(m=>`<li>${m}</li>`).join('')}</ul><p class="case-meta">Срок и итоговая стоимость этого объекта не опубликованы.</p>${button('Рассчитать похожий проект','/#quiz')}<a class="source-link" href="${p.source}" target="_blank" rel="noopener">Объект на сайте ArtBalkon ↗</a></div></div></section>${contact()}`;}
